### ISSUE TITLE
TypeError: 'str' object is not callable

### ISSUE THREAD

**Issue by michaelsstuff** [Katello/katello-client-bootstrap#213]
Hi,

I tested with a rhel 6.9 host, which is deployed and registered via satellite 5, and tried to move it to satellite 6 with the current version of this script. 
It does register it against the new satellite, remove it from the old, also installes the certificate, but then breaks with 

`[RUNNING], [2017-09-05 14:04:43], [/sbin/chkconfig rhsmcertd on]

[SUCCESS], [2017-09-05 14:04:43], [/sbin/chkconfig rhsmcertd on], completed successfully.

Traceback (most recent call last):
  File "bootstrap.py", line 1052, in <module>
    migrate_systems(options.org, options.activationkey)
  File "bootstrap.py", line 299, in migrate_systems
    enable_rhsmcertd()
  File "bootstrap.py", line 268, in enable_rhsmcertd
    exec_service("rhsmcertd", "restart")
  File "bootstrap.py", line 803, in exec_service
    exec_failexit("/sbin/service %s %s %" (service, command))
TypeError: 'str' object is not callable
`
It does not yet have installed the katello-agent or the puppet agent. 
May sound a bit fuzzy, sorry. If I can create any logs or debug info let me know, as I can reproduce this issue.

Best regards
Michael

**Comment by michaelsstuff** [comment]
Tested it with the fix, works now.
Thank you very much!
